---

mongoUri: "mongodb://192.168.99.100/reports?connectTimeoutMS=5000&socketTimeoutMS=90000&w=majority&j=true&wtimeoutMS=60000"

selfUrl: "http://localhost:8080"

logging:
  level: INFO

  loggers:
    "example": DEBUG
