server:
  type: default
  rootPath: /api
  minThreads:  12
  maxThreads: 48
  maxQueuedRequests: 2048
  idleThreadTimeout: 10 seconds

mongoUri: "mongodb://192.168.99.100/reports?connectTimeoutMS=5000&socketTimeoutMS=90000&w=majority&j=true&wtimeoutMS=60000"

logging:
  level: INFO

  loggers:
    "io.dropwizard": DEBUG
    "io.testscucumber": DEBUG

# metrics:
#   frequency: 1 minute
#   reporters:
#     - type: graphite
#       host: 192.168.99.100
#       port: 2003
#       prefix: tests-cucumber
